# For more information see:
# https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run type checks
        run: deno task check-types

      - name: Run code-style checks
        run: deno task check-lint

      - name: Run fmt checks
        run: deno task check-fmt
